import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react";
import AuthProvider from './providers'; // 引入我們剛剛建立的客戶端元件
import { ThemeProvider } from './providers/theme-provider';
// 'use client'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ThemeProvider>
          <AuthProvider> */}
            {children}
          {/* </AuthProvider>
        </ThemeProvider> */}
        {/* <SessionProvider>
          {children}
        </SessionProvider> */}

      </body>
    </html>
  );
}
