import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "./providers/ThemeProvider";
import ThemeToggle from "./components/ThemeToggle";
import { AuthProvider } from "./auth/hooks/useAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
          <Toaster
            richColors={true}
            toastOptions={{
              classNames: {
                // 應用於 success 類型的 Toast
                success: 'bg-green-600 text-white',
                // 應用於 error 類型的 Toast
                error: 'bg-red-600 text-white',
              }
            }} />
        </ThemeProvider>

      </body>
    </html>
  );
}
